// Product catalogue — designsys.md §16 (card/hover), §17 (badges), §24 (variants), §44 (data model).
// Prices are LKR integers. releaseDate values are fixed ISO strings — never computed.

// Types come from @/types/* — the §44 contract. This file is seed data only and
// deliberately declares no shapes of its own: a second local `Product` would
// drift from the one components import, and `images` would lose its alt text.
import type { Product, ProductImage, ProductVariant } from "@/types/product";

export type { Product, ProductVariant };

// Title-case the slug into human alt text. `imgs()` is only ever called with the
// product's OWN slug (verified across all 30 entries), so this describes the
// right product. Alt is required by @/types/product — a11y is not optional.
const altFromSlug = (slug: string): string =>
  slug
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");

const imgs = (slug: string): ProductImage[] => {
  const alt = altFromSlug(slug);
  return [
    { id: `${slug}-img-1`, url: `https://picsum.photos/seed/${slug}-1/800/800`, alt, width: 800, height: 800 },
    { id: `${slug}-img-2`, url: `https://picsum.photos/seed/${slug}-2/800/800`, alt: `${alt} — alternate view`, width: 800, height: 800 },
  ];
};


// Seed rows omit `status` and `variants` because both are derivable: status is a
// pure function of stock, and most products have no variation axis. `mk()` fills
// them so the exported array is a real §44 `Product[]` with nothing optional.
// Variant images inherit the parent's — the seed has no per-variant photography.
type ProductSeed = Omit<Product, "status" | "variants" | "images"> & {
  images: ProductImage[];
  variants?: Array<Omit<ProductVariant, "images">>;
};

const mk = (seed: ProductSeed): Product => ({
  ...seed,
  status: seed.stock > 0 ? "ACTIVE" : "SOLD_OUT",
  variants: (seed.variants ?? []).map((variant) => ({ ...variant, images: seed.images })),
});

export const products: Product[] = [
  mk({
    id: "prd-001",
    name: "Proof (Standard Edition)",
    slug: "bts-proof-standard-edition",
    artistId: "art-bts",
    categoryId: "cat-albums",
    description:
      "Three-disc anthology tracing a decade of singles, unreleased demos and solo cuts, with a 96-page photobook per version.",
    price: 12800,
    compareAtPrice: 15500,
    stock: 42,
    images: imgs("bts-proof-standard-edition"),
    variants: [
      {
        id: "var-001-a",
        productId: "prd-001",
        name: "Standard",
        sku: "BTS-PRF-STD",
        price: 12800,
        stock: 42,
        attributes: { version: "STANDARD", edition: "3CD + Photobook" },
      },
      {
        id: "var-001-b",
        productId: "prd-001",
        name: "Compact",
        sku: "BTS-PRF-CMP",
        price: 8400,
        stock: 18,
        attributes: { version: "COMPACT", edition: "1CD + Mini Photobook" },
      },
      {
        id: "var-001-c",
        productId: "prd-001",
        name: "Collector Set",
        sku: "BTS-PRF-SET",
        price: 28000,
        stock: 4,
        attributes: { version: "SET", edition: "All 3 versions + Poster Tube" },
      },
    ],
    releaseDate: "2025-06-10T00:00:00.000Z",
    isPreorder: false,
    isFeatured: true,
    isLimited: false,
    createdAt: "2025-06-01T00:00:00.000Z",
  }),
  mk({
    id: "prd-002",
    name: "ARMY Bomb Ver. 4",
    slug: "bts-army-bomb-ver-4",
    artistId: "art-bts",
    categoryId: "cat-lightsticks",
    description:
      "Official fourth-generation lightstick with Bluetooth venue sync, adjustable brightness and a matte charcoal grip.",
    price: 24500,
    stock: 3,
    images: imgs("bts-army-bomb-ver-4"),
    releaseDate: "2025-03-18T00:00:00.000Z",
    isPreorder: false,
    isFeatured: true,
    isLimited: true,
    createdAt: "2025-03-10T00:00:00.000Z",
  }),
  mk({
    id: "prd-003",
    name: "Proof Photocard Set — Full Member",
    slug: "bts-proof-photocard-set",
    artistId: "art-bts",
    categoryId: "cat-photocards",
    description: "Seven-card official set pulled from the Proof standard pressing, sleeved and toploaded.",
    price: 4200,
    compareAtPrice: 5600,
    stock: 27,
    images: imgs("bts-proof-photocard-set"),
    releaseDate: "2025-06-10T00:00:00.000Z",
    isPreorder: false,
    isFeatured: false,
    isLimited: false,
    createdAt: "2025-06-12T00:00:00.000Z",
  }),
  mk({
    id: "prd-004",
    name: "BORN PINK Photocard Set",
    slug: "blackpink-born-pink-photocard-set",
    artistId: "art-blackpink",
    categoryId: "cat-photocards",
    description: "Four-member official set from the BORN PINK box, including the pre-order bonus card.",
    price: 3600,
    stock: 64,
    images: imgs("blackpink-born-pink-photocard-set"),
    releaseDate: "2025-01-22T00:00:00.000Z",
    isPreorder: false,
    isFeatured: true,
    isLimited: false,
    createdAt: "2025-01-20T00:00:00.000Z",
  }),
  mk({
    id: "prd-005",
    name: "BORN PINK (Deluxe Boxset)",
    slug: "blackpink-born-pink-deluxe-boxset",
    artistId: "art-blackpink",
    categoryId: "cat-albums",
    description:
      "Heavyweight boxset with lenticular cover, 128-page photobook, poster set and a numbered authenticity card.",
    price: 28000,
    stock: 2,
    images: imgs("blackpink-born-pink-deluxe-boxset"),
    releaseDate: "2025-01-22T00:00:00.000Z",
    isPreorder: false,
    isFeatured: true,
    isLimited: true,
    createdAt: "2025-01-15T00:00:00.000Z",
  }),
  mk({
    id: "prd-006",
    name: "BLACKPINK World Tour Hoodie",
    slug: "blackpink-world-tour-hoodie",
    artistId: "art-blackpink",
    categoryId: "cat-apparel",
    description: "Heavyweight brushed-fleece hoodie with tour routing printed across the back panel.",
    price: 14500,
    compareAtPrice: 18000,
    stock: 0,
    images: imgs("blackpink-world-tour-hoodie"),
    releaseDate: "2025-04-05T00:00:00.000Z",
    isPreorder: false,
    isFeatured: false,
    isLimited: false,
    createdAt: "2025-04-01T00:00:00.000Z",
  }),
  mk({
    id: "prd-007",
    name: "ODDINARY (Scanning Ver.)",
    slug: "stray-kids-oddinary-scanning",
    artistId: "art-stray-kids",
    categoryId: "cat-albums",
    description: "Mini album in the Scanning jacket, with folded poster, sticker sheet and a random member card.",
    price: 9800,
    stock: 58,
    images: imgs("stray-kids-oddinary-scanning"),
    variants: [
      {
        id: "var-007-a",
        productId: "prd-007",
        name: "Standard",
        sku: "SKZ-ODD-STD",
        price: 9800,
        stock: 58,
        attributes: { version: "STANDARD", edition: "Scanning Ver." },
      },
      {
        id: "var-007-b",
        productId: "prd-007",
        name: "Compact",
        sku: "SKZ-ODD-CMP",
        price: 6900,
        stock: 31,
        attributes: { version: "COMPACT", edition: "Mask Off Ver." },
      },
      {
        id: "var-007-c",
        productId: "prd-007",
        name: "Set",
        sku: "SKZ-ODD-SET",
        price: 17400,
        stock: 9,
        attributes: { version: "SET", edition: "Both versions + Poster" },
      },
    ],
    releaseDate: "2025-02-14T00:00:00.000Z",
    isPreorder: false,
    isFeatured: true,
    isLimited: false,
    createdAt: "2025-02-10T00:00:00.000Z",
  }),
  mk({
    id: "prd-008",
    name: "NACHIMBONG Ver. 2 Lightstick",
    slug: "stray-kids-nachimbong-ver-2",
    artistId: "art-stray-kids",
    categoryId: "cat-lightsticks",
    description: "Compass-motif official lightstick with a weighted base and three concert colour modes.",
    price: 23000,
    stock: 21,
    images: imgs("stray-kids-nachimbong-ver-2"),
    releaseDate: "2025-05-30T00:00:00.000Z",
    isPreorder: false,
    isFeatured: false,
    isLimited: false,
    createdAt: "2025-05-25T00:00:00.000Z",
  }),
  mk({
    id: "prd-009",
    name: "Stray Kids Tour Tee — Black",
    slug: "stray-kids-tour-tee-black",
    artistId: "art-stray-kids",
    categoryId: "cat-apparel",
    description: "Boxy-fit cotton tee with a tonal front crest and full date list on the reverse.",
    price: 7200,
    stock: 5,
    images: imgs("stray-kids-tour-tee-black"),
    releaseDate: "2025-07-02T00:00:00.000Z",
    isPreorder: false,
    isFeatured: false,
    isLimited: false,
    createdAt: "2025-07-01T00:00:00.000Z",
  }),
  mk({
    id: "prd-010",
    name: "FML (Deluxe Ver.)",
    slug: "seventeen-fml-deluxe",
    artistId: "art-seventeen",
    categoryId: "cat-albums",
    description: "Tenth mini album in the deluxe jacket, with a 120-page photobook and an unreleased polaroid print.",
    price: 13600,
    compareAtPrice: 16200,
    stock: 37,
    images: imgs("seventeen-fml-deluxe"),
    releaseDate: "2025-04-24T00:00:00.000Z",
    isPreorder: false,
    isFeatured: true,
    isLimited: false,
    createdAt: "2025-04-18T00:00:00.000Z",
  }),
  mk({
    id: "prd-011",
    name: "CARAT Bong Ver. 3",
    slug: "seventeen-carat-bong-ver-3",
    artistId: "art-seventeen",
    categoryId: "cat-lightsticks",
    description: "Diamond-cut official lightstick with a rose-gold shaft and app-controlled sync.",
    price: 22800,
    stock: 14,
    images: imgs("seventeen-carat-bong-ver-3"),
    releaseDate: "2026-11-28T00:00:00.000Z",
    isPreorder: true,
    isFeatured: false,
    isLimited: false,
    createdAt: "2025-08-01T00:00:00.000Z",
  }),
  mk({
    id: "prd-012",
    name: "SEVENTEEN Season's Greetings 2026",
    slug: "seventeen-seasons-greetings-2026",
    artistId: "art-seventeen",
    categoryId: "cat-official-merch",
    description: "Desk calendar, A4 planner, sticker book and a thirteen-card photo set in a linen-wrapped case.",
    price: 19500,
    stock: 11,
    images: imgs("seventeen-seasons-greetings-2026"),
    releaseDate: "2026-12-05T00:00:00.000Z",
    isPreorder: true,
    isFeatured: true,
    isLimited: true,
    createdAt: "2025-09-01T00:00:00.000Z",
  }),
  mk({
    id: "prd-013",
    name: "READY TO BE (To Ver.)",
    slug: "twice-ready-to-be-to-ver",
    artistId: "art-twice",
    categoryId: "cat-albums",
    description: "Twelfth mini album in the To jacket, with lyric book, photocard and a folded group poster.",
    price: 9400,
    stock: 49,
    images: imgs("twice-ready-to-be-to-ver"),
    releaseDate: "2025-03-10T00:00:00.000Z",
    isPreorder: false,
    isFeatured: false,
    isLimited: false,
    createdAt: "2025-03-05T00:00:00.000Z",
  }),
  mk({
    id: "prd-014",
    name: "CANDY BONG ∞",
    slug: "twice-candy-bong-infinity",
    artistId: "art-twice",
    categoryId: "cat-lightsticks",
    description: "Third-generation candy lightstick with a frosted dome and a removable wrist strap.",
    price: 21500,
    compareAtPrice: 24000,
    stock: 8,
    images: imgs("twice-candy-bong-infinity"),
    releaseDate: "2025-02-28T00:00:00.000Z",
    isPreorder: false,
    isFeatured: true,
    isLimited: false,
    createdAt: "2025-02-20T00:00:00.000Z",
  }),
  mk({
    id: "prd-015",
    name: "TWICE Acrylic Keyring Set",
    slug: "twice-acrylic-keyring-set",
    artistId: "art-twice",
    categoryId: "cat-accessories",
    description: "Nine-piece acrylic keyring set with double-sided printing and brushed steel clasps.",
    price: 5800,
    stock: 73,
    images: imgs("twice-acrylic-keyring-set"),
    releaseDate: "2025-05-16T00:00:00.000Z",
    isPreorder: false,
    isFeatured: false,
    isLimited: false,
    createdAt: "2025-05-14T00:00:00.000Z",
  }),
  mk({
    id: "prd-016",
    name: "Armageddon (Deluxe Boxset)",
    slug: "aespa-armageddon-deluxe-boxset",
    artistId: "art-aespa",
    categoryId: "cat-albums",
    description: "First full-length in a magnetic-close boxset with holographic sleeve and four member photobooks.",
    price: 26500,
    stock: 6,
    images: imgs("aespa-armageddon-deluxe-boxset"),
    releaseDate: "2025-05-27T00:00:00.000Z",
    isPreorder: false,
    isFeatured: true,
    isLimited: true,
    createdAt: "2025-05-20T00:00:00.000Z",
  }),
  mk({
    id: "prd-017",
    name: "aespa Photocard Binder",
    slug: "aespa-photocard-binder",
    artistId: "art-aespa",
    categoryId: "cat-accessories",
    description: "Ring binder with thirty acid-free nine-pocket sleeves and a padded chrome-print cover.",
    price: 8900,
    stock: 34,
    images: imgs("aespa-photocard-binder"),
    releaseDate: "2025-06-19T00:00:00.000Z",
    isPreorder: false,
    isFeatured: false,
    isLimited: false,
    createdAt: "2025-06-15T00:00:00.000Z",
  }),
  mk({
    id: "prd-018",
    name: "aespa POB Photocard — Winter",
    slug: "aespa-pob-photocard-winter",
    artistId: "art-aespa",
    categoryId: "cat-photocards",
    description: "Pre-order bonus card from the Armageddon Japan pressing, in mint condition with a toploader.",
    price: 1200,
    stock: 1,
    images: imgs("aespa-pob-photocard-winter"),
    releaseDate: "2025-05-27T00:00:00.000Z",
    isPreorder: false,
    isFeatured: false,
    isLimited: true,
    createdAt: "2025-05-30T00:00:00.000Z",
  }),
  mk({
    id: "prd-019",
    name: "I'VE MINE (Blink Ver.)",
    slug: "ive-ive-mine-blink-ver",
    artistId: "art-ive",
    categoryId: "cat-albums",
    description: "First EP in the Blink jacket, with a 76-page photobook, bookmark and a random member card.",
    price: 10200,
    compareAtPrice: 12000,
    stock: 44,
    images: imgs("ive-ive-mine-blink-ver"),
    releaseDate: "2025-04-13T00:00:00.000Z",
    isPreorder: false,
    isFeatured: false,
    isLimited: false,
    createdAt: "2025-04-09T00:00:00.000Z",
  }),
  mk({
    id: "prd-020",
    name: "IVE Official Bucket Hat",
    slug: "ive-official-bucket-hat",
    artistId: "art-ive",
    categoryId: "cat-apparel",
    description: "Washed cotton bucket hat with an embroidered logo tab and a taped interior seam.",
    price: 6400,
    stock: 4,
    images: imgs("ive-official-bucket-hat"),
    releaseDate: "2025-07-21T00:00:00.000Z",
    isPreorder: false,
    isFeatured: false,
    isLimited: false,
    createdAt: "2025-07-18T00:00:00.000Z",
  }),
  mk({
    id: "prd-021",
    name: "IVE SHOW WHAT I HAVE Photobook",
    slug: "ive-show-what-i-have-photobook",
    artistId: "art-ive",
    categoryId: "cat-official-merch",
    description: "196-page tour photobook on uncoated stock, with a gatefold poster and backstage contact sheets.",
    price: 16800,
    stock: 19,
    images: imgs("ive-show-what-i-have-photobook"),
    releaseDate: "2025-08-08T00:00:00.000Z",
    isPreorder: false,
    isFeatured: true,
    isLimited: false,
    createdAt: "2025-08-04T00:00:00.000Z",
  }),
  mk({
    id: "prd-022",
    name: "EASY (Vibe Ver.)",
    slug: "le-sserafim-easy-vibe-ver",
    artistId: "art-le-sserafim",
    categoryId: "cat-albums",
    description: "Third mini album in the Vibe jacket, with a 64-page photobook, postcard and folded poster.",
    price: 9600,
    stock: 52,
    images: imgs("le-sserafim-easy-vibe-ver"),
    releaseDate: "2025-02-19T00:00:00.000Z",
    isPreorder: false,
    isFeatured: false,
    isLimited: false,
    createdAt: "2025-02-15T00:00:00.000Z",
  }),
  mk({
    id: "prd-023",
    name: "LE SSERAFIM Varsity Jacket",
    slug: "le-sserafim-varsity-jacket",
    artistId: "art-le-sserafim",
    categoryId: "cat-apparel",
    description: "Wool-blend varsity with leather sleeves, chenille lettering and a quilted satin lining.",
    price: 27500,
    compareAtPrice: 32000,
    stock: 3,
    images: imgs("le-sserafim-varsity-jacket"),
    releaseDate: "2025-09-12T00:00:00.000Z",
    isPreorder: false,
    isFeatured: true,
    isLimited: true,
    createdAt: "2025-09-08T00:00:00.000Z",
  }),
  mk({
    id: "prd-024",
    name: "GET UP (Bunny Beach Bag ver.)",
    slug: "newjeans-get-up-bunny-beach-bag-ver",
    artistId: "art-newjeans",
    categoryId: "cat-albums",
    description: "Second EP packaged inside a woven beach bag, with a zine, sticker sheet and two member cards.",
    price: 15200,
    stock: 23,
    images: imgs("newjeans-get-up-bunny-beach-bag-ver"),
    variants: [
      {
        id: "var-024-a",
        productId: "prd-024",
        name: "Standard",
        sku: "NJ-GTU-STD",
        price: 15200,
        stock: 23,
        attributes: { version: "STANDARD", edition: "Bunny Beach Bag ver." },
      },
      {
        id: "var-024-b",
        productId: "prd-024",
        name: "Compact",
        sku: "NJ-GTU-CMP",
        price: 8600,
        stock: 40,
        attributes: { version: "COMPACT", edition: "Weverse Album ver." },
      },
      {
        id: "var-024-c",
        productId: "prd-024",
        name: "Set",
        sku: "NJ-GTU-SET",
        price: 23000,
        stock: 0,
        attributes: { version: "SET", edition: "All versions + Tote" },
      },
    ],
    releaseDate: "2025-07-21T00:00:00.000Z",
    isPreorder: false,
    isFeatured: true,
    isLimited: false,
    createdAt: "2025-07-15T00:00:00.000Z",
  }),
  mk({
    id: "prd-025",
    name: "NewJeans Bunny Phone Case",
    slug: "newjeans-bunny-phone-case",
    artistId: "art-newjeans",
    categoryId: "cat-accessories",
    description: "Shock-absorbing case with a soft-touch finish and a detachable bunny charm on a woven cord.",
    price: 6800,
    stock: 87,
    images: imgs("newjeans-bunny-phone-case"),
    releaseDate: "2025-08-30T00:00:00.000Z",
    isPreorder: false,
    isFeatured: false,
    isLimited: false,
    createdAt: "2025-08-26T00:00:00.000Z",
  }),
  mk({
    id: "prd-026",
    name: "NewJeans Photocard Set — GET UP",
    slug: "newjeans-get-up-photocard-set",
    artistId: "art-newjeans",
    categoryId: "cat-photocards",
    description: "Five-member official set from the GET UP standard pressing, sleeved and shipped rigid.",
    price: 3200,
    compareAtPrice: 4100,
    stock: 0,
    images: imgs("newjeans-get-up-photocard-set"),
    releaseDate: "2025-07-21T00:00:00.000Z",
    isPreorder: false,
    isFeatured: false,
    isLimited: false,
    createdAt: "2025-07-24T00:00:00.000Z",
  }),
  mk({
    id: "prd-027",
    name: "Fe3O4: BREAK (Standard)",
    slug: "nmixx-fe3o4-break-standard",
    artistId: "art-nmixx",
    categoryId: "cat-albums",
    description: "Third EP in the standard jacket, with a 80-page photobook, folded poster and two random cards.",
    price: 9200,
    stock: 38,
    images: imgs("nmixx-fe3o4-break-standard"),
    releaseDate: "2026-10-30T00:00:00.000Z",
    isPreorder: true,
    isFeatured: false,
    isLimited: false,
    createdAt: "2025-09-10T00:00:00.000Z",
  }),
  mk({
    id: "prd-028",
    name: "NMIXX Fanmeeting Goods Pack",
    slug: "nmixx-fanmeeting-goods-pack",
    artistId: "art-nmixx",
    categoryId: "cat-official-merch",
    description: "Slogan towel, badge set, mini poster and a signed-print reproduction in a rigid mailer.",
    price: 11400,
    stock: 2,
    images: imgs("nmixx-fanmeeting-goods-pack"),
    releaseDate: "2025-06-06T00:00:00.000Z",
    isPreorder: false,
    isFeatured: false,
    isLimited: true,
    createdAt: "2025-06-02T00:00:00.000Z",
  }),
  mk({
    id: "prd-029",
    name: "BTS Tour Tote — Yet To Come",
    slug: "bts-tour-tote-yet-to-come",
    artistId: "art-bts",
    categoryId: "cat-accessories",
    description: "Heavy canvas tote with reinforced handles, an interior zip pocket and a screen-printed crest.",
    price: 7600,
    stock: 56,
    images: imgs("bts-tour-tote-yet-to-come"),
    releaseDate: "2025-04-30T00:00:00.000Z",
    isPreorder: false,
    isFeatured: false,
    isLimited: false,
    createdAt: "2025-04-27T00:00:00.000Z",
  }),
  mk({
    id: "prd-030",
    name: "BLACKPINK Official Merch Box",
    slug: "blackpink-official-merch-box",
    artistId: "art-blackpink",
    categoryId: "cat-official-merch",
    description: "Season box with a slogan, badge set, photo prints and a numbered membership card.",
    price: 18400,
    stock: 15,
    images: imgs("blackpink-official-merch-box"),
    releaseDate: "2025-09-19T00:00:00.000Z",
    isPreorder: false,
    isFeatured: false,
    isLimited: false,
    createdAt: "2025-09-15T00:00:00.000Z",
  }),
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByArtist(artistId: string): Product[] {
  return products.filter((p) => p.artistId === artistId);
}

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter((p) => p.categoryId === categoryId);
}

export const featuredProducts: Product[] = products.filter((p) => p.isFeatured);

// Three distinct 8-item slices — same catalogue, different editorial cut.
const bySlugs = (slugs: readonly string[]): Product[] =>
  slugs
    .map((slug) => products.find((p) => p.slug === slug))
    .filter((p): p is Product => p !== undefined);

export const trendingProducts: Product[] = bySlugs([
  "bts-proof-standard-edition",
  "blackpink-born-pink-deluxe-boxset",
  "stray-kids-oddinary-scanning",
  "newjeans-get-up-bunny-beach-bag-ver",
  "seventeen-fml-deluxe",
  "aespa-armageddon-deluxe-boxset",
  "twice-candy-bong-infinity",
  "le-sserafim-varsity-jacket",
]);

export const fanFavorites: Product[] = bySlugs([
  "bts-army-bomb-ver-4",
  "blackpink-born-pink-photocard-set",
  "twice-acrylic-keyring-set",
  "newjeans-bunny-phone-case",
  "seventeen-carat-bong-ver-3",
  "stray-kids-nachimbong-ver-2",
  "aespa-photocard-binder",
  "ive-ive-mine-blink-ver",
]);

// Disjoint from the two rails above on purpose — the homepage shows all three,
// so a shared slug is the same card twice on one scroll. data.check.ts asserts it.
export const newDropProducts: Product[] = bySlugs([
  "blackpink-official-merch-box",
  "newjeans-get-up-photocard-set",
  "nmixx-fanmeeting-goods-pack",
  "ive-show-what-i-have-photobook",
  "ive-official-bucket-hat",
  "stray-kids-tour-tee-black",
  "seventeen-seasons-greetings-2026",
  "nmixx-fe3o4-break-standard",
]);
